apiVersion: v1
kind: Secret
metadata:
  name: ebitda-secret
  namespace: ebitda
type: Opaque
stringData:
  APP_KEY: "<base64:production-app-key>"
  DB_USERNAME: "<db-username>"
  DB_PASSWORD: "<db-password>"
  REDIS_PASSWORD: "<redis-password-or-null>"
  PORTAL_PEMBANGUNAN_SARPRAS_TOKEN: "<portal-token>"
  SSO_CLIENT_SECRET: "<sso-client-secret>"
