apiVersion: v1
kind: ConfigMap
metadata:
  name: ebitda-redis-ca
  namespace: ebitda
  labels:
    app.kubernetes.io/name: ebitdamax-apn
    environment: staging
data:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIID7TCCAtWgAwIBAgIBADANBgkqhkiG9w0BAQsFADCBhTEtMCsGA1UELhMkMzA2
    Yjk1OTgtM2IxYi00M2RmLWI4NzgtZDE3MjdhMmEzODMwMTEwLwYDVQQDEyhHb29n
    bGUgQ2xvdWQgTWVtb3J5c3RvcmUgUmVkaXMgU2VydmVyIENBMRQwEgYDVQQKEwtH
    b29nbGUsIEluYzELMAkGA1UEBhMCVVMwHhcNMjYwODMxMDg0OTM5WhcNMzYwODI4
    MDg1MDM5WjCBhTEtMCsGA1UELhMkMzA2Yjk1OTgtM2IxYi00M2RmLWI4NzgtZDE3
    MjdhMmEzODMwMTEwLwYDVQQDEyhHb29nbGUgQ2xvdWQgTWVtb3J5c3RvcmUgUmVk
    aXMgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUsIEluYzELMAkGA1UEBhMCVVMw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCykIaeDSRYt+mGGZxX526+
    CNo0YZHBS3SsRDm+gyDSJGhZuMV35IKXT1yvEcRLmGH32/z6nKick5SXxv2OJ+Ku
    OmpHDFXS+bXSNNhkGhBN055ZqDEVCxLXy7E7sb50uoSQI44VvALIhorTJ0YWz1dz
    Ob4iA7CIINDq8ceBJK/j/1p5pcTo9BqkR0kYOXqp5+Cc/+6jApThO8TKq1ydsn9n
    PFk5iZ6q0NZlpdJa75z3RT59405f6FyYQFjoXLbYIiYSIAFBDYn6FERkGAFNCS+Q
    iDBEuA4uYTZmpEdrMdLI3/VeFlm4/S8dau8n5tabNE9BUKAyQtUngMhKd28wcIoD
    AgMBAAGjZjBkMB8GA1UdIwQYMBaAFJH3/wgRCkj570jMRRAYaEQHYMPGMBIGA1Ud
    EwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBSR9/8IEQpI
    +e9IzEUQGGhEB2DDxjANBgkqhkiG9w0BAQsFAAOCAQEApDz/NpPw5QrFZetyQUAu
    ZKdOkGDVMFoAf5aA3ZI+vDuvGjIamnJrHfIdms+RQ4Fw8Y21iLBm95cp/Qr40qOr
    ShdJxDCXLMRY1fpJyKyxO+f4a9NspBwWucuccoo0H8eyO0Ox3ug7eTYzNUl/QPr0
    bDtPPOx5G3nGjt+Jm7hA8+8IhAGnvrQUYrNCz46SD2u/SStP0CEBZV373sBeEDom
    2HFaPvnYg1+FsI5jXQQXQrqsGQBnHUOHoxqIdTz8YQ0KDnXIHsCz5SA/xvF6PaLj
    7MBiq6t9ZLfgrirO9Q/82ybzDrfFJunR9bRWYMj1xSnmOfQIM5X1j4HAkFh9c+cc
    NA==
    -----END CERTIFICATE-----
