apiVersion: v1
kind: ConfigMap
metadata:
  name: ebitda-redis-ca
  namespace: ebitda
  labels:
    app.kubernetes.io/name: ebitda
    environment: production
data:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIID7TCCAtWgAwIBAgIBADANBgkqhkiG9w0BAQsFADCBhTEtMCsGA1UELhMkNmU1
    ZTU4ZGItMjQzMS00OTlkLThlNWEtODAwN2MzMjdlZWJmMTEwLwYDVQQDEyhHb29n
    bGUgQ2xvdWQgTWVtb3J5c3RvcmUgUmVkaXMgU2VydmVyIENBMRQwEgYDVQQKEwtH
    b29nbGUsIEluYzELMAkGA1UEBhMCVVMwHhcNMjYwOTE3MTAyODE3WhcNMzYwOTE0
    MTAyOTE3WjCBhTEtMCsGA1UELhMkNmU1ZTU4ZGItMjQzMS00OTlkLThlNWEtODAw
    N2MzMjdlZWJmMTEwLwYDVQQDEyhHb29nbGUgQ2xvdWQgTWVtb3J5c3RvcmUgUmVk
    aXMgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUsIEluYzELMAkGA1UEBhMCVVMw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJinIIY+9H2ElF4QAyIpIn
    /d6GiYg1C3SVsXmHzBtXICGoXAPQRTYOPUOc/h2FJA8m/s6t6zc9RFcoaFsu6w9P
    5fTEuSHwRVQHVH28O0ZfpqLvvwmSmfcBFXTY+zhJre2ganzjM7JBWbbz6qUlbA+9
    LiOqMcA92DsBUoiliXXBOO1FS4tTS42jR/QktetFdYNr76wyGb5L2ga2IKSif5zP
    IERB5hLKGy8xfVthuxbxiKP/RNv6qaKEw3pz45zhuL1msE1f/hjD7ipTvsNxajMb
    mYHl7MtFIzbD0pdF8nCLYgwyGAWJmxd01FifNe8+2C5zSdGV2LO3zUl8aOTVXEo1
    AgMBAAGjZjBkMB8GA1UdIwQYMBaAFOmmbU/7jYnyPOj2dFRM57EbwdhuMBIGA1Ud
    EwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBTppm1P+42J
    8jzo9nRUTOexG8HYbjANBgkqhkiG9w0BAQsFAAOCAQEAmc7kOxd5QnP0+DOMXN5a
    NS9F+1mynY3y/cRw9dNppS9q7sfEKSrfMX4sjzC5f1mQY82cePRGoa9cMxFmaUgu
    Oci/7ePaYGH2VcZFtHLAAzHrUePxcaMP+7rHILkzrt3z+DAXxb86Qsvjd56eR2Qm
    hSvoF0r4H2wNX3v8zMezRlBnxTPXwa4ZXtX189VbgDm/4+Ti9HtUedbdF001tfv2
    iFbFWbu3QLhPuW4H+DT+87vT5l+rX2gIYnYxVYUJFpeS5hJixkagbcnNUXdFL5/D
    5Y+21TDZQw+0baG+BDgFwXEaYGmOtXwn3ILE2JZlE7Khbi4utZ/kYaft3IluOtZV
    UQ==
    -----END CERTIFICATE-----
