apiVersion: v1
kind: ConfigMap
metadata:
  name: ebitda-redis-ca
  namespace: ebitda
  labels:
    app.kubernetes.io/name: ebitda
    environment: production
data:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIID7TCCAtWgAwIBAgIBADANBgkqhkiG9w0BAQsFADCBhTEtMCsGA1UELhMkZjNk
    ZmQ5NzctOTliNy00ZDk2LTg1ZDUtYmNjMjAyZDMxMzE2MTEwLwYDVQQDEyhHb29n
    bGUgQ2xvdWQgTWVtb3J5c3RvcmUgUmVkaXMgU2VydmVyIENBMRQwEgYDVQQKEwtH
    b29nbGUsIEluYzELMAkGA1UEBhMCVVMwHhcNMjYwOTE0MDY1NTU3WhcNMzYwOTEx
    MDY1NjU3WjCBhTEtMCsGA1UELhMkZjNkZmQ5NzctOTliNy00ZDk2LTg1ZDUtYmNj
    MjAyZDMxMzE2MTEwLwYDVQQDEyhHb29nbGUgQ2xvdWQgTWVtb3J5c3RvcmUgUmVk
    aXMgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUsIEluYzELMAkGA1UEBhMCVVMw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCU/c05vWzK0N2yXS831Gv0
    TrS7UKoyypGBgsrIJ5zCJxk3qAEEPeYojxDDoPh/cN2gc4m9e5A0wWLOqJCGSsS+
    H87JOAqxWR51kQo6aJGXFwpu86FpfEPJkJ208bQFKbdo287868FOWyIvsnaQvFDm
    W5B2uUO0dALtfJjjBZ5nQV3bosXCqyUiEZzR7zEfWxB0SIRYR7YwBOiDHcQe03Ye
    1grhUAttFo7HXh6bPNs/ns3YaaWa7z0SYFGz41swkQFaInf8/kGfyKZm77Tq+oKO
    XRLXLn9k5p9kC3USEiRCIPT7vKVRe76B0z7wNbgKzEm+OZ5XRIZrSA2f5dWnPpA1
    AgMBAAGjZjBkMB8GA1UdIwQYMBaAFFt5OZRxWCbfzBKJ0Fn1C5fmxER3MBIGA1Ud
    EwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBRbeTmUcVgm
    38wSidBZ9QuX5sREdzANBgkqhkiG9w0BAQsFAAOCAQEAeF8YHjhKcyfCcIlIKfno
    KKku1HaJAUzxp/PsiyYdKZJt4QF78kPQyLpvPlKoIcs83+jt/i7D16irjC7f1RBL
    EJYnb8LwnyprqpQeP3v3QDFk13Ihm+L72D2jfxCFVsXlO+6oCQwgP4g/i4KFetQM
    iPUbWIZ/Kk/1OVYvx++NJeyIS15f8uZePNj7Hx5mBoRov2m64mlpbZ8r6ReBl0eG
    PZfbnR+ysmV9OUr6KjJq5we+0+20s92ssZ45ts6G1FPPlydQbwNkJxhhq3vk88yx
    MNTBZYYpZhPSArwvAaB+4+Qb2zXXfZLjJjr+yqQctEPGJ19pZsaxkZ8ECAw/+ivD
    wQ==
    -----END CERTIFICATE-----
