apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebitda
  namespace: ebitda
  annotations:
    iam.gke.io/gcp-service-account: apn-production-ebitda@dev-agrinas.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: ebitda
    environment: production
